apiVersion: v1
kind: PersistentVolume
metadata:
    name: elk-pv
    namespace: elk
spec:
  capacity: 
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-storage
  local: 
    path: /opt/elasticsearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - minikube-m02
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: local-storage
    namespace: elk
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: elk-pv-claim
    namespace: elk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi