apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  serviceName: elastic-search-headless
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pr-con
        image: justwatch/elasticsearch_exporter:1.0.2
        ports:
        - containerPort: 9108
        args: ['-es.uri=http://localhost:9200']
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 9200
          name: es-node-0
          protocol: TCP
        - containerPort: 9300
          name: es-node-1
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: "elastic-search"
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: es-cluster-0.elastic-search-headless,es-cluster-1.elastic-search-headless
          - name: cluster.initial_master_nodes
            value: es-cluster-0,es-cluster-1
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: node.roles
            value: master,data  
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mystorage
      resources:
        requests:
          storage: 250Mi
 